# Generated by Django 3.2 on 2022-07-13 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateField(auto_now_add=True)),
                ('store', models.CharField(max_length=200)),
                ('weight_kg', models.FloatField()),
                ('department', models.CharField(choices=[('Bakery', 'Bakery'), ('Dairy', 'Dairy'), ('Deli', 'Deli'), ('Grocery', 'Grocery'), ('MeatSeafood', 'Meat/Seafood'), ('Produce', 'Produce'), ('Other', 'Other')], max_length=11)),
                ('notes', models.CharField(blank=True, max_length=1024, null=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.destination')),
            ],
        ),
    ]
