# Generated by Django 3.2 on 2022-08-30 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_company_stage_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiversionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.stage'),
        ),
        migrations.AddField(
            model_name='store',
            name='diversion_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.diversiontype'),
        ),
    ]
