# Generated by Django 3.2 on 2022-09-02 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20220830_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='donation',
            name='store',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='diversion_type',
            field=models.ForeignKey(default='App Only', on_delete=django.db.models.deletion.CASCADE, to='backend.diversiontype'),
        ),
    ]
